[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyblackjack"
version = "0.9.0"
description = "A CLI Blackjack Game played against the dealer."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []